import { ROLE_USER } from "./Role";

const FUNCTION_ROLE = {
  [ROLE_USER.SUPER_USER]: {
    CREATE_USER: "CREATE_USER",
    LOCK_USER: "LOCK_USER",
    DELETE_USER: "DELETE_USER",
    TRANSFER_ROLE: "TRANSFER_ROLE",
    SEE_STATUS_GAME: "SEE_STATUS_GAME",
    LOCK_GAME: "LOCK_GAME",
  },
  [ROLE_USER.ADMIN]: {
    CREATE_USER: "CREATE_USER",
    DELETE_USER: "DELETE_USER",
    ASSIGNMENT_USER: "ASSIGNMENT_USER",
  },
  [ROLE_USER.CREATE_GAME]: {
    CREATE_URL: "CREATE_URL",
    TYPE_GAME: "TYPE_GAME",
    SCALE: "SCALE",
    FEE: "FEE",
  },
  [ROLE_USER.END_GAME]: {
    
  },
  [ROLE_USER.INPUT_TOKEN]: {},
  [ROLE_USER.WITHDRAW_TOKEN]: {},
  [ROLE_USER.USER]: {},
};

export const FUNCTION_ADMIN = Object.freeze(FUNCTION_ROLE.ADMIN);
export const FUNCTION_SUPPER_USER = Object.freeze(FUNCTION_ROLE.SUPER_USER);
export const FUNCTION_CREATE_USER = Object.freeze(FUNCTION_ROLE.CREATE_GAME);
export const FUNCTION_END_GAME = Object.freeze(FUNCTION_ROLE.END_GAME);
export const FUNCTION_INPUT_TOKEN = Object.freeze(FUNCTION_ROLE.INPUT_TOKEN);
export const FUNCTION_WITHDRAW_TOKEN = Object.freeze(FUNCTION_ROLE.WITHDRAW_TOKEN);
export const FUNCTION_USER = Object.freeze(FUNCTION_ROLE.USER);
